### ISSUE TITLE
SQLite Error 14: 'unable to open database file'

### ISSUE THREAD

**Issue by kenthub** [markjprice/cs8dotnetcore3#13]
https://github.com/markjprice/cs8dotnetcore3/blob/95cccd934c4a9a0034d49e31d728622a89d6e985/PracticalApps/NorthwindMvc/Controllers/HomeController.cs#L36

For some reason, it is not finding my Northwind.db file. 
I have it in the Practical App folder along with my projects.

Practical App
>NorthwindWeb
>NorthwindMvc
>Northwind.db

**locahost/5001** error page
```
A database operation failed while processing the request.
SqliteException: SQLite Error 14: 'unable to open database file'.
Use migrations to create the database for Northwind
In Visual Studio, use the Package Manager Console to scaffold a new migration and apply it to the database:

PM> Add-Migration [migration name]
PM> Update-Database
Alternatively, you can scaffold a new migration and apply it from a command prompt at your project directory:

> dotnet ef migrations add [migration name]
> dotnet ef database update
```

**Terminal Error Message**
```
      Content root path: C:\Users\username\source\repos\cs8dotnetcore3\Practical Apps\NorthwindMvc
fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
      An error occurred using the connection to database 'main' on server '..:Northwind.db'.
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'NorthwindContextLib.Northwind'.
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteConnection.Open()
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
         at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
```

**NorthwindMvc.csproj**
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>aspnet-NorthwindMvc-AA6B766E-8F35-4AB9-B13C-CD685F43084D</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Update="app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\NorthwindContextLib\NorthwindContextLib.csproj" />
      <ProjectReference
      Include="..\NorthwindEntityLib\NorthwindEntityLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.3" />
  </ItemGroup>

</Project>
```

**HomeController.cs**
```
        private readonly Northwind db;

        public HomeController(ILogger<HomeController> logger, Northwind injectedContext)
        {
            _logger = logger;
            db = injectedContext;
        }

        public IActionResult Index()
        {

            var model = new HomeIndexViewModel
            {
                VisitorCount = (new Random().Next(1, 1001)),
                Categories = db.Categories.ToList(),
                Products = db.Products.ToList()
            };

            return View(model);
        }
```

**Comment by markjprice** [comment]
The path to the database file is set on Line 33 in Startup.cs so that's where I recommend that you start looking to fix your issue:
https://github.com/markjprice/cs8dotnetcore3/blob/master/PracticalApps/NorthwindMvc/Startup.cs#L33

**Comment by kenthub** [comment]
Thanks! 

I was calling `ConfigurationPath.Combine` and not `Path.Combine`

I appreciate the response!
